//! Core data models for sus

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

/// Risk level assessment for a package
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, sqlx::Type)]
#[sqlx(type_name = "varchar", rename_all = "lowercase")]
#[serde(rename_all = "lowercase")]
pub enum RiskLevel {
    Clean,
    Warning,
    Critical,
}

impl RiskLevel {
    pub fn emoji(&self) -> &'static str {
        match self {
            RiskLevel::Clean => "✅",
            RiskLevel::Warning => "⚠️",
            RiskLevel::Critical => "🚨",
        }
    }
}

/// Types of agentic threats that can be detected
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, sqlx::Type)]
#[sqlx(type_name = "varchar", rename_all = "snake_case")]
#[serde(rename_all = "snake_case")]
pub enum ThreatType {
    PromptInjection,
    InstructionOverride,
    DataExfiltration,
    SocialEngineering,
    InstallScriptInjection,
    MaliciousCode,
}

/// Priority levels for scan jobs
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ScanPriority {
    Low = 0,
    Medium = 1,
    High = 2,
    Immediate = 3,
}

/// A package scan result stored in the database
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Package {
    pub id: i32,
    pub name: String,
    pub version: String,
    pub risk_level: RiskLevel,
    pub risk_reasons: serde_json::Value,
    pub trust_score: Option<i16>,
    pub publisher_verified: Option<bool>,
    pub weekly_downloads: Option<i64>,
    pub maintainer_count: Option<i32>,
    pub last_publish: Option<DateTime<Utc>>,
    pub capabilities: serde_json::Value,
    pub skill_md: Option<String>,
    pub scanned_at: DateTime<Utc>,
    pub scan_version: Option<String>,
}

/// CVE information linked to a package
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct PackageCve {
    pub id: i32,
    pub package_id: i32,
    pub cve_id: String,
    pub severity: Option<String>,
    pub description: Option<String>,
    pub fixed_in: Option<String>,
    pub published_at: Option<DateTime<Utc>>,
}

/// Agentic threat detected in a package
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct AgenticThreat {
    pub id: i32,
    pub package_id: i32,
    pub threat_type: ThreatType,
    pub confidence: f32,
    pub location: Option<String>,
    pub snippet: Option<String>,
    pub detected_at: DateTime<Utc>,
}

/// Network capabilities of a package
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct NetworkCapabilities {
    pub makes_requests: bool,
    pub domains: Vec<String>,
    pub protocols: Vec<String>,
}

/// Filesystem capabilities of a package
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FilesystemCapabilities {
    pub reads: bool,
    pub writes: bool,
    pub paths: Vec<PathPermission>,
}

/// Path permission entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PathPermission {
    pub path: String,
    pub mode: String, // "r", "w", "rw"
}

/// Process capabilities of a package
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ProcessCapabilities {
    pub spawns_children: bool,
    pub commands: Vec<String>,
}

/// Environment capabilities of a package
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EnvironmentCapabilities {
    pub accessed_vars: Vec<String>,
}

/// Native module capabilities
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct NativeCapabilities {
    pub has_native: bool,
    pub native_modules: Vec<String>,
}

/// Combined package capabilities
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PackageCapabilities {
    pub network: NetworkCapabilities,
    pub filesystem: FilesystemCapabilities,
    pub process: ProcessCapabilities,
    pub environment: EnvironmentCapabilities,
    pub native: NativeCapabilities,
}

/// Usage documentation for a package (generated by AI)
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UsageDocs {
    /// Package description/summary
    pub description: Option<String>,
    /// Quick start code example
    pub quick_start: Option<String>,
    /// Key APIs and their usage
    pub key_apis: Vec<ApiDoc>,
    /// Best practices for using this package
    pub best_practices: Vec<String>,
    /// Common patterns and idioms
    pub common_patterns: Vec<String>,
    /// Common gotchas or pitfalls to avoid
    pub gotchas: Vec<String>,
}

/// Documentation for a single API/function
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiDoc {
    /// Name of the API (function, class, method)
    pub name: String,
    /// Brief description
    pub description: String,
    /// Example usage
    pub example: Option<String>,
}

/// A job in the scan queue
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScanJob {
    pub id: Uuid,
    pub package: String,
    pub version: Option<String>,
    pub priority: ScanPriority,
    pub requested_at: DateTime<Utc>,
    pub requested_by: Option<String>, // "user", "watcher", "cve-update"
    /// Optional path to a local tarball (for scanning uploaded packages)
    pub tarball_path: Option<String>,
}

impl ScanJob {
    pub fn new(package: String, version: Option<String>, priority: ScanPriority) -> Self {
        Self {
            id: Uuid::new_v4(),
            package,
            version,
            priority,
            requested_at: Utc::now(),
            requested_by: None,
            tarball_path: None,
        }
    }

    /// Create a job for scanning a local tarball
    pub fn from_tarball(package: String, version: String, tarball_path: String) -> Self {
        Self {
            id: Uuid::new_v4(),
            package,
            version: Some(version),
            priority: ScanPriority::Immediate,
            requested_at: Utc::now(),
            requested_by: Some("tarball-upload".to_string()),
            tarball_path: Some(tarball_path),
        }
    }
}

/// CVE summary for API responses
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CveSummary {
    pub cve_id: String,
    pub severity: Option<String>,
    pub description: Option<String>,
    pub fixed_in: Option<String>,
}

/// Agentic threat summary for API responses
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgenticThreatSummary {
    pub threat_type: ThreatType,
    pub confidence: f32,
    pub location: Option<String>,
    pub snippet: Option<String>,
}

/// Publisher information
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PublisherInfo {
    pub name: Option<String>,
    pub verified: bool,
}

/// Install script information
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct InstallScripts {
    pub preinstall: bool,
    pub install: bool,
    pub postinstall: bool,
    pub prepare: bool,
}

impl InstallScripts {
    pub fn has_any(&self) -> bool {
        self.preinstall || self.install || self.postinstall || self.prepare
    }

    pub fn count(&self) -> usize {
        [
            self.preinstall,
            self.install,
            self.postinstall,
            self.prepare,
        ]
        .iter()
        .filter(|&&v| v)
        .count()
    }
}

/// Full package response for API
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PackageResponse {
    pub name: String,
    pub version: String,
    pub risk_level: RiskLevel,
    pub risk_reasons: Vec<String>,
    pub trust_score: Option<u8>,
    pub publisher: Option<PublisherInfo>,
    pub weekly_downloads: Option<u64>,
    pub install_scripts: InstallScripts,
    pub cves: Vec<CveSummary>,
    pub agentic_threats: Vec<AgenticThreatSummary>,
    pub capabilities: PackageCapabilities,
    pub skill_md: Option<String>,
    pub scanned_at: DateTime<Utc>,
}

/// Request to scan a package
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScanRequest {
    pub name: String,
    pub version: Option<String>,
}

/// Response after requesting a scan
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScanRequestResponse {
    pub job_id: Uuid,
    pub estimated_seconds: u32,
}

/// Bulk lookup request
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BulkLookupRequest {
    pub packages: Vec<PackageVersionPair>,
}

/// Package name and version pair
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PackageVersionPair {
    pub name: String,
    pub version: String,
}

/// npm package metadata from registry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NpmPackageMetadata {
    pub name: String,
    pub description: Option<String>,
    #[serde(rename = "dist-tags")]
    pub dist_tags: Option<serde_json::Value>,
    pub versions: Option<serde_json::Value>,
    pub maintainers: Option<Vec<NpmMaintainer>>,
    pub repository: Option<serde_json::Value>,
}

/// npm maintainer info
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NpmMaintainer {
    pub name: Option<String>,
    pub email: Option<String>,
}

/// npm package version info
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NpmVersionInfo {
    pub name: String,
    pub version: String,
    pub description: Option<String>,
    pub main: Option<String>,
    pub scripts: Option<serde_json::Value>,
    pub dependencies: Option<serde_json::Value>,
    #[serde(rename = "devDependencies")]
    pub dev_dependencies: Option<serde_json::Value>,
    pub dist: Option<NpmDist>,
}

/// npm distribution info
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NpmDist {
    pub tarball: Option<String>,
    pub shasum: Option<String>,
    pub integrity: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_risk_level_serialization() {
        // Test serialization
        assert_eq!(
            serde_json::to_string(&RiskLevel::Clean).unwrap(),
            "\"clean\""
        );
        assert_eq!(
            serde_json::to_string(&RiskLevel::Warning).unwrap(),
            "\"warning\""
        );
        assert_eq!(
            serde_json::to_string(&RiskLevel::Critical).unwrap(),
            "\"critical\""
        );

        // Test deserialization
        assert_eq!(
            serde_json::from_str::<RiskLevel>("\"clean\"").unwrap(),
            RiskLevel::Clean
        );
        assert_eq!(
            serde_json::from_str::<RiskLevel>("\"warning\"").unwrap(),
            RiskLevel::Warning
        );
        assert_eq!(
            serde_json::from_str::<RiskLevel>("\"critical\"").unwrap(),
            RiskLevel::Critical
        );
    }

    #[test]
    fn test_risk_level_emoji() {
        assert_eq!(RiskLevel::Clean.emoji(), "✅");
        assert_eq!(RiskLevel::Warning.emoji(), "⚠️");
        assert_eq!(RiskLevel::Critical.emoji(), "🚨");
    }

    #[test]
    fn test_threat_type_serialization() {
        assert_eq!(
            serde_json::to_string(&ThreatType::PromptInjection).unwrap(),
            "\"prompt_injection\""
        );
        assert_eq!(
            serde_json::to_string(&ThreatType::DataExfiltration).unwrap(),
            "\"data_exfiltration\""
        );

        assert_eq!(
            serde_json::from_str::<ThreatType>("\"prompt_injection\"").unwrap(),
            ThreatType::PromptInjection
        );
        assert_eq!(
            serde_json::from_str::<ThreatType>("\"social_engineering\"").unwrap(),
            ThreatType::SocialEngineering
        );
    }

    #[test]
    fn test_scan_job_creation() {
        let job = ScanJob::new(
            "express".to_string(),
            Some("4.18.0".to_string()),
            ScanPriority::High,
        );

        assert_eq!(job.package, "express");
        assert_eq!(job.version, Some("4.18.0".to_string()));
        assert_eq!(job.priority, ScanPriority::High);
        assert!(job.tarball_path.is_none());
        assert!(job.requested_by.is_none());
    }

    #[test]
    fn test_scan_job_from_tarball() {
        let job = ScanJob::from_tarball(
            "my-package".to_string(),
            "1.0.0".to_string(),
            "/tmp/my-package.tgz".to_string(),
        );

        assert_eq!(job.package, "my-package");
        assert_eq!(job.version, Some("1.0.0".to_string()));
        assert_eq!(job.priority, ScanPriority::Immediate);
        assert_eq!(job.tarball_path, Some("/tmp/my-package.tgz".to_string()));
        assert_eq!(job.requested_by, Some("tarball-upload".to_string()));
    }

    #[test]
    fn test_install_scripts_has_any() {
        let empty = InstallScripts::default();
        assert!(!empty.has_any());
        assert_eq!(empty.count(), 0);

        let with_postinstall = InstallScripts {
            postinstall: true,
            ..Default::default()
        };
        assert!(with_postinstall.has_any());
        assert_eq!(with_postinstall.count(), 1);

        let with_multiple = InstallScripts {
            preinstall: true,
            postinstall: true,
            prepare: true,
            ..Default::default()
        };
        assert!(with_multiple.has_any());
        assert_eq!(with_multiple.count(), 3);
    }

    #[test]
    fn test_scan_priority_ordering() {
        assert!(ScanPriority::Low < ScanPriority::Medium);
        assert!(ScanPriority::Medium < ScanPriority::High);
        assert!(ScanPriority::High < ScanPriority::Immediate);
    }
}
